### ISSUE TITLE
Support for needed cards.

### ISSUE THREAD

**Issue by IlyaHalsky** [ko-vasilev/Hearthstone-Collection-Tracker#10]
Currently plugin only shows chance of dropping new cards for you collection. But what if you need only 1 card and other 57 missing are useless or not played these days?

**Comment by ko-vasilev** [comment]
Hey, I understand your point and I initially thought about this feature.
Still thinking about how would it better to implement, maybe add a checkbox near each card like "Need".

**Comment by IlyaHalsky** [comment]
@ko-vasilev Yea, just add a switch from your collection to cards you need. And 1 more question: "opening odds" is a chance to open new card for your collection?

**Comment by ko-vasilev** [comment]
Yes, it is a chance to open at least one missing card from pack.
