### ISSUE TITLE
Collection Tracker 0.5.0 threw an exception

### ISSUE THREAD

**Issue by claudioboccuni89** [ko-vasilev/Hearthstone-Collection-Tracker#105]
Collection tracker today doesn't work.
This the log
[hdt_log.txt](https://github.com/ko-vasilev/Hearthstone-Collection-Tracker/files/629695/hdt_log.txt)

**Comment by adriencarbonne** [comment]
Hello @claudioboccuni89 
You can use my new version which adds compatibility with Mean Streets of Gadgetzan and fixes the compatibility issue with Hearthstone Tracker latest version: https://github.com/adriencarbonne/Hearthstone-Collection-Tracker/releases

**Comment by claudioboccuni89** [comment]
Thank you very much!
