### ISSUE TITLE
Interaction between HDT and HCT?

### ISSUE THREAD

**Issue by IlyaHalsky** [ko-vasilev/Hearthstone-Collection-Tracker#11]
DId you think about interactions between HDT and HCT? Imagine: I'm importing deck from hearthhead or something, and I'm missing 2 cards. Friendly reminder from HCT pops up and says witch packs I need to buy, to accomplish imported deck.

Sorry for explanation, if you didn't get something feel free to ask.

**Comment by ko-vasilev** [comment]
Thanks for the idea, I will check if it is possible to do. Unfortunately I guess developer of HDT did not provide any API of communicating with import process.

**Comment by IlyaHalsky** [comment]
Btw, to earn some style points, can you add something like pic of Antonidas, saying "I suggest buying %type_of_pack packs would be better for your collection"?

**Comment by ko-vasilev** [comment]
Haha that would be gorgeous :D I'll think what can I do with it.
