### ISSUE TITLE
Шанс меняется при добавлении первой копии карты из двух.

### ISSUE THREAD

**Issue by Decavoid** [ko-vasilev/Hearthstone-Collection-Tracker#12]
При добавлении в коллекцию 1-й копии карты Common/Rare/Epic плагин показывает уменьшение шанса дропа новой карты. 
Пример:
Пустая коллекция. Плагин показывает шанс открытия новой Common карты 99,76%.
Добавляю 1-ю копию карты Naturalize. Плагин уменьшает шанс до 99,74%. Это неверно, шанс должен остаться неизменным.

**Comment by ko-vasilev** [comment]
Привет, спасибо за отзыв. Да, возможно лучше переделать логику таким образом.

Basically what Andrey said is that it is incorrect when you add one card out of two, chances of opening missing card lowers.
