### ISSUE TITLE
Can't get it to find plug-in.

### ISSUE THREAD

**Issue by ifhbiff** [ko-vasilev/Hearthstone-Collection-Tracker#15]
I've followed the instructions multiple times; deleted and reinstalled the .dll.  Each time, I go to Properties and Unblock, then select Apply and/or OK.  But when I go to HDT, no Plug Ins are found, and when I go back to the properties of the dll, the Unblock option is still there (I don't know if it greys out when the Unblock works).  I'm at a total loss, feel like I've been trying this for weeks.

**Comment by ifhbiff** [comment]
![collection_tracker_issue1](https://cloud.githubusercontent.com/assets/13473795/8860975/5b47c124-3155-11e5-8574-9c5020982170.jpg)
![collection_tracker_issue2](https://cloud.githubusercontent.com/assets/13473795/8860977/5ccb9c3c-3155-11e5-952f-56e2de2bd2b5.jpg)

**Comment by ifhbiff** [comment]
![collection_tracker_issue1](https://cloud.githubusercontent.com/assets/13473795/8860990/7ed48ee2-3155-11e5-93df-4b9552f0bd40.jpg)
![collection_tracker_issue2](https://cloud.githubusercontent.com/assets/13473795/8860991/7fe2b408-3155-11e5-8fee-d5b4ff86028c.jpg)

**Comment by ko-vasilev** [comment]
Hello! Please note that you also have to enable the plugin in settings:
http://screencast.com/t/XaJOGtt3WNy

**Comment by ifhbiff** [comment]
I don't even have the collection tracker window to select that enable.  That's kinda the point.
![collection_tracker_issue3](https://cloud.githubusercontent.com/assets/13473795/8881178/df444bbc-320b-11e5-8363-fa50b565c283.jpg)

**Comment by ko-vasilev** [comment]
Can you please try installing some other plugins? I cannot tell if it is not loaded because of me or not
https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Available-Plugins

I think the answer is yes, but did you relaunch HDT after adding the plugin in Plugins folder?
