### ISSUE TITLE
Multiple region support

### ISSUE THREAD

**Issue by GiggliG** [ko-vasilev/Hearthstone-Collection-Tracker#17]
Does this support keeping separate collections for separate regions yet?

**Comment by ko-vasilev** [comment]
I'm planning to release a new version soon! This feature is already implemented.

**Comment by GiggliG** [comment]
do you mean multiple region support is already in the current release?

**Comment by ko-vasilev** [comment]
I did not release a new version yet. You will be notified through plugin when it will be available!
