### ISSUE TITLE
Different way of importing from Hearthstone?

### ISSUE THREAD

**Issue by scottismyname** [ko-vasilev/Hearthstone-Collection-Tracker#19]
So I just built a version with all of the latest commits (including importing from Hearthstone), and I must say it's pretty great! (there's a few visual bugs with buttons have the wrong text, etc.)

I'm wondering if it's possible to make the process more efficient though.  I noticed that the way it works is that it basically just searches for every card and if it detects it (not sure if it uses image recognition or if it uses the log file in some sort).

Would it be possible to have it instead view the full collection and do image recognition for each of the positions where cards would possibly be?  Then "flip the page" after it's done processing each page of cards.

Just thought I'd throw it out there.  Overall, on the normal speed setting, I think it took less than 5 minutes to go through the entire collection (which is already updated with TGT cards!).

Thanks for this awesome plugin!

**Comment by ko-vasilev** [comment]
Hey, thanks for the feedback! About importing process, I don't find it necessary to complex it using some kind of image recognition, current logic is much simplier and runs at decent speed.

Can you please tell me which visual bugs did you encounter?

**Comment by scottismyname** [comment]
Ok I understand.

Regarding the visual bugs, the entire screen doesn't fit vertically and there doesn't appear to be a scroll button?  The second bug is that (for me at least) when you open the settings from within HDT, the window that pops up is too small to fit all the content.

Minor suggestions:
1) Make the import/settings available from within the plugin instead of having to do it from within HDT plugin settings.
2) Change the text from "Import from game" to "Import from Collection".  The title as it is now is a bit misleading.

**Comment by ko-vasilev** [comment]
Please download latest version and check it again. I guess it should be okay now.

**Comment by scottismyname** [comment]
New changes look great!  Now if we could just add the import settings to the main collection tracker window :)

**Comment by ko-vasilev** [comment]
I just think that Importing is the feature that will be used 1 time per half a year (at best) so it is not necessary to flud the main screen with this functionality.
