### ISSUE TITLE
Missing cards. 

### ISSUE THREAD

**Issue by FenrisWolffe** [ko-vasilev/Hearthstone-Collection-Tracker#2]
Many are in the wrong collections, will compile a list tomorrow. 
Naxx and BRM are missing?
Also, must it be manually updated on every card gain?

**Comment by ko-vasilev** [comment]
Yes you have to manually update it.
I included here only the cards that can be acquired from the packs (Classic and GVG) so there will be no Basic/Naxx/BRM/Non-collectable cards.

**Comment by FenrisWolffe** [comment]
You closed the issue, but, many of the cards are still in the wrong category.

**Comment by ko-vasilev** [comment]
Can you provide an example? I haven't found any cards to be in wrong category.

**Comment by FenrisWolffe** [comment]
Naturalize was the first I saw.

**Comment by ko-vasilev** [comment]
Maybe you added two of them and that's why it is not shown in your list?
![image](https://cloud.githubusercontent.com/assets/5964618/7666513/9e37f95e-fc12-11e4-8f40-5b66c3255e45.png)
Are you using English language?

**Comment by FenrisWolffe** [comment]
It shows in the list, but it shows under the wrong category. Or it did. I will provide a list and screenshots when I am able to sit down.

**Comment by AlSom1** [comment]
Hello there, and sorry to bother you in the first place. I do not understand the reason for not including Naxx & BrM Cards. It would make deck constructing and importing/exporting so easier. Please consider adding this as an option! Thank you for the time you might spend on it!

**Comment by ko-vasilev** [comment]
Hey, I just don't think it is necessary because the main puprose of the plugin is to track cards you might want to craft or decide to maybe buy packs if you missing alot of them.
With adventure cards you can only buy adventure wings to get them, so it is pretty straightforward with this.

**Comment by MeSko** [comment]
Why I think is necessary because is very annoying when plugin show card that you have as missing.. wrrr

Please change one line in:
Hearthstone Collection Tracker\SetCardsManager.cs

`public static readonly string[] CollectableSets = { "Classic", "Goblins vs Gnomes", "The Grand Tournament", "Curse of Naxxramas", "Blackrock Mountain", "League of Explorers", "Reward", "Promotion"};`
