### ISSUE TITLE
Hide desired cards

### ISSUE THREAD

**Issue by culinko** [ko-vasilev/Hearthstone-Collection-Tracker#21]
Hello again. First of all, I would like to thank you so much for the new version of this amazing plugin, you did a really great job! Well done.

However, I find the "Desired" cards column along with the numbers in flyout redundant, because I won't use the function and I don't really like the duplicate info much. I would like to request an option to hide both the column and the numbers in the flyout. Since the plugin has no options, one possible way could be to integrate it somewhere into the UI, for example to the right side of "Average dust value" for each set.

What do you think, would this be possible? Many thanks once again for the amazing update.

**Comment by ko-vasilev** [comment]
Hello, thanks for your feedback.
Just so you know, plugin have settings window (accessible from HDT options -> Plugins -> Collection Tracker -> Settings).

I think this is a nice option to have, I'll definitely look forward to implement it.

**Comment by culinko** [comment]
Oh nice, that's good to know. Thanks for the quick reply.

**Comment by gabessdsp** [comment]
I'd like to ditto this suggestion. I don't really care for cards others "desire" I desire them all so that is my goal.

**Comment by promethyttrium** [comment]
Can you please explain the "desired" card feature to me? Are those the cards that are missing from my collection? In truth, I would desire them all so I can have a complete set of all the cards available.

**Comment by culinko** [comment]
If you don't want to collect some cards (e.g. Kidnapper), you can change the desired cards on Kidnapper from 2 to 0 and it would not count them towards the complete collection. If you desire all the cards, you are on the same boat as us who responded to this issue to have the option and the display of desired cards hidden completely.

**Comment by ventus93** [comment]
It don't work... I can't find any option to disable Desired Card feature...

**Comment by ko-vasilev** [comment]
@ventus93 it will be included in the next release.
