### ISSUE TITLE
Next HDT Update

### ISSUE THREAD

**Issue by azeier** [ko-vasilev/Hearthstone-Collection-Tracker#23]
The next HDT update will most likely require some (minor) changes for your plugin to properly work.

See here for more info and a pre-release download: https://github.com/Epix37/HDT-Test/releases/tag/v0.10.12PRE3

**Comment by ko-vasilev** [comment]
Okay, thank you for the info.
I have one question: is there any way I can access existing GameV2 object? I need its IsRunning property.

**Comment by azeier** [comment]
You can now download the latest pre-release here: https://github.com/Epix37/HDT-Test/releases

**Comment by azeier** [comment]
If I find no more major problems the update should go out [11am UTC](http://everytimezone.com/#2015-8-24,-60,cn3).
