### ISSUE TITLE
Right click to show missing cards and required dust.

### ISSUE THREAD

**Issue by SuperWig** [ko-vasilev/Hearthstone-Collection-Tracker#29]
So right now, from what I can tell it only shows you what you're missing when you go to save a deck, but if you want to see what you're missing again you have to edit the deck and then save it again. I thought it would be nice to also have an option to right click a deck and have an option to show you any missing cards.

Also it would be nice to also have the amount of dust required to craft the missing cards in this window.

**Comment by ko-vasilev** [comment]
Thank you for the idea! Unfortunately, as I believe currently there is no way of doing this for me.
@Epix37 any ideas?

**Comment by promethyttrium** [comment]
As a compromise, is it possible for when you notify the cards are missing, add that to the deck's notes? If not, please at least make the message be in readonly textbox (so I can select the text and copy it into the clipboard so I can add it as a note to the deck myself without typing it all in (or add a copy message button) :) )

Thanks for a great plugin!

**Comment by azeier** [comment]
Since HDT already has a similar feature that will show you the cards that were missing in the last export, you should be able to just do:

``` C#
deck.MissingCards = missingCards.Select(x =>
            {
                x.Item1.Count = x.Item2;
                return x.Item1;
            }).ToList();
```

at the end of `HearthstoneCollectionTrackerPlugin.HandleHearthstoneDeckUpdated`.

**Comment by ko-vasilev** [comment]
@Epix37 Thanks for the suggestion, will try this out!

**Comment by Kerredai** [comment]
I second this request; I think it'd really add a lot to the plugin if it could calculate the dust cost to craft the missing cards and either paste that directly into the deck notes or at least display it as text that could be manually copied over.

**Comment by elbaso** [comment]
Sorry for the "me-too" comment, but I would also very much like this feature implemented.
Any updates on if Epix's suggested change gets the job done?
