### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by draav** [ko-vasilev/Hearthstone-Collection-Tracker#30]
I have been trying to update the colelction manager for a few days on and off. In the installation page it says:

"Unzip Hearthstone.Collection.Tracker.zip archive from release page to Plugins folder in root of your Hearthstone Deck Tracker. Then enable it in the Settings menu."

then it talks about a .dll file.

When I try to just put the folder in the plugins folder nothing happens or changes. Also there is [no .dll](http://i.imgur.com/LF0qCut.png) file in the zipped file from the [release page](https://github.com/ko-vasilev/Hearthstone-Collection-Tracker/releases/tag/0.2.2).

Not sure if I'm just missing something dumb. I'm not exactly sure how to update the colelction tracker without losing the information about my currently owned cards.

**Comment by SuperWig** [comment]
I'm pretty sure you're downloading the wrong file. You should be downloading the .rar, the other files are the source code.

**Comment by ko-vasilev** [comment]
Yes, sorry It's my mistake. You should be downloading .rar file, I'll update the installation instructions shortly.

**Comment by draav** [comment]
Okay, thank you! Sorry for not understanding.

**Comment by ko-vasilev** [comment]
No problem, thank you for pointing it out! Even the smallest bugs should be fixed :)
