### ISSUE TITLE
Mass dispel imports as gold

### ISSUE THREAD

**Issue by razko** [ko-vasilev/Hearthstone-Collection-Tracker#32]
I have 1x Mass Dispel card (non-gold), and every time I import collection, it imports it as a golden card. I've tried to do this twice on fresh profiles, once with fast speed, once with normal, and both times I got the same result.

**Comment by ko-vasilev** [comment]
Yes, it is a known issue with importing some of Priest cards.

**Comment by ko-vasilev** [comment]
Duplicate of #26
