### ISSUE TITLE
Plugin not compatible with HDT 0.12.x

### ISSUE THREAD

**Issue by ptournet** [ko-vasilev/Hearthstone-Collection-Tracker#38]
I'm discovering HDT and its plugins andn as of 2 days ago a new version 0.12.0 of HDT was released that could break some plugins according to the release notes...

As I can't get HCT to work (and especially, getting an error message saying that "Collection Tracker 0.2.2 is not compatible with HDT 0.12.1"), I guess that it's one of those...

**Comment by KayaTheRock** [comment]
I have the same issue. Here is the crash output, maybe it can help.

![screenhunter_127 oct 16 02 05](https://cloud.githubusercontent.com/assets/14054739/10529871/56f29b70-73aa-11e5-8bd8-0870f88c488a.jpg)

**Comment by Litvan** [comment]
Yup, same error here.
![error](https://cloud.githubusercontent.com/assets/15156240/10539561/a0e06388-7400-11e5-82e7-1c2c9b13710f.jpg)

**Comment by Adster** [comment]
I recompiled HCT against the newest HDT source and it now works fine for me.  

It would be great if we can get an official release here, but in the meantime I uploaded a release on my fork if you'd like to give it a try

https://github.com/Adster/Hearthstone-Collection-Tracker/releases/tag/0.2.2

**Comment by Litvan** [comment]
Lovely mate... I'll give it a twirl once I get home again ^^
But yeah... An offical update would be nice.

**Comment by ptournet** [comment]
Thanks a lot ! I was planning to do it myself but VS2015 install takes ages !

**Comment by Litvan** [comment]
Well I ain't home yet so... Might be an hour or so more from now on

**Comment by KayaTheRock** [comment]
Adster's release worked fine.

Thanks a bunch!

**Comment by Litvan** [comment]
Like Kaya wrote... works like a charm Adster, tyvm

**Comment by ko-vasilev** [comment]
@Adster thank you for your rather quick fix :) I will release a hotfix shortly.

**Comment by Adster** [comment]
Glad i was able to help :)
