### ISSUE TITLE
There are no folder called "Plugins"

### ISSUE THREAD

**Issue by IlyaHalsky** [ko-vasilev/Hearthstone-Collection-Tracker#4]
subj

EDT1: after creating folder manually, HDT still can't see Plugin (i unblocked .dll file).

**Comment by ko-vasilev** [comment]
So you created "Plugins" folder in the root of HDT, re-launched the HDT and plugin is still not in Settings list?

**Comment by SoldierOfGod87** [comment]
Im having the same issue. 

Downloaded File Dll, Extracted to desktop > Created Folder named (Plugins) here > me - AppData - Roaming - HearthstoneDeckTracker.
copied .dll file to the Plugins folder I created > restarted HDT - Options - Plugins and nothing is there. any suggestions ?

Fyi I went in the .dll properties and I dont have that option to Block or unblock like in the pictures.

**Comment by ko-vasilev** [comment]
@SoldierOfGod87 "Plugins" folder should be created in the same folder where your HDT .exe file is located

**Comment by IlyaHalsky** [comment]
@ko-vasilev I did it at home dir of HDT, still no effect

**Comment by VeXHarbinger** [comment]
I also have this issue, and I don't see any issues in the log window. 
Are their some keywords I should look for?  I assume you are handling for spaces in the pathing location.  I've installed mine at "E:\Documents\GitHub\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Plugins"

Could one of the path properties need to be set if we don't have it installed in the typical path location?

Also in "Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Plugins" I have the following files;
- PluginManager.cs
- PluginWrapper.cs
- IPlugin.cs
- PluginSettings.cs

Is this expected, or have any bearing on this issue?  I'm running my own compiled version if that matters.

**Comment by ko-vasilev** [comment]
@VeXHarbinger the dll file should be put in the Plugins folder of you binaries (where executable is located). So in your case for example it will be "E:\Documents\GitHub\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\bin\debug\Plugins\"

**Comment by VeXHarbinger** [comment]
That did it, I can now see it in the plugin tab.  Tyvm for the prompt reply.  Hope that this helps other folks down the road as well.
