### ISSUE TITLE
Link up shop in hearthstone and Collection Tracker

### ISSUE THREAD

**Issue by IlyaHalsky** [ko-vasilev/Hearthstone-Collection-Tracker#5]
Is it possible to link up store and Collection Tracker, so it would launch, when i buy/open packs?

**Comment by azeier** [comment]
From logs: no.
On opening the "open packs" screen can be detected but at that point you might aswell just go to the app.

Image recognition might work.

**Comment by IlyaHalsky** [comment]
@Epix37 since you are there, any tips on how to capture HDT in OBS?

**Comment by azeier** [comment]
OBS can't capture transparent windows, so capturing the overlay only works if you use screencapture. Currently the only alternative is to turn on the external deck windos via `options > overlay > deck windows` and capture those.
