### ISSUE TITLE
Collection not saved between program launches?

### ISSUE THREAD

**Issue by flatluigi** [ko-vasilev/Hearthstone-Collection-Tracker#56]
I don't know if there's a bug or if it's intended behavior, but whenever I import my collection it only stays imported until I close HDT, then it wipes the entire saved data and I have to re-import. Is this intended, somehow? If it's not, what can I do to fix this?

**Comment by ko-vasilev** [comment]
Hello, this actually might be a bug. Please try after import - open plugin window and close it. This should force collection to be saved.
Thank you.
