### ISSUE TITLE
Collection Tracker v0.2.4 crashes with HDT 0.13.7

### ISSUE THREAD

**Issue by joeshoukry** [ko-vasilev/Hearthstone-Collection-Tracker#60]
Collection tracker keeps throwing an exception: 

I'm using latest builds of both CT and HDT - I'm new to this so not sure if I am doing something wrong

![image](https://cloud.githubusercontent.com/assets/10981458/12011878/a9c02fe2-ac95-11e5-92a8-98f73d2b8c87.png)

**Comment by miggat** [comment]
The same happens to me. Just updated both HDT and CT. Well it's a different exception actually.
![error_hdt_ct](https://cloud.githubusercontent.com/assets/4322303/12115340/be4f6e78-b3b1-11e5-864c-5a6b601bfab4.PNG)

**Comment by ko-vasilev** [comment]
@joeshoukry @miggat Guys please try again with new release.

**Comment by miggat** [comment]
Just updated and I have the same error. (btw the dll is unlocked)

**Comment by riQQ** [comment]
@miggat looks like your config is corrupt. Can you upload it? It's located at `%APPDATA%\HearthstoneDeckTracker\CollectionTracker\config.xml`.

**Comment by miggat** [comment]
It was corrupt indeed. I opened it on Notepad++ and it was a bunch of null characters. At least it was nothing like xml.
I deleted it and now I can load the plugin, but when I try to import collection, the plugin (and the hole HDT app) crashes. Not sure if this is a different problem or I need well-formatted config file.

**Comment by miggat** [comment]
BTW the new config file looks like this:

`<?xml version="1.0" encoding="utf-8"?>
<PluginSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <CurrentVersion>
    <Major>0</Major>
    <Minor>3</Minor>
    <Build>0</Build>
    <Revision>-1</Revision>
  </CurrentVersion>
  <ActiveAccount>Default</ActiveAccount>
  <Accounts>
    <AccountSummary>
      <AccountName>Default</AccountName>
      <FileStoragePath>MY_USER_FOLDER\AppData\Roaming\HearthstoneDeckTracker\CollectionTracker\Collection_Default.xml</FileStoragePath>
    </AccountSummary>
  </Accounts>
  <CollectionWindowWidth>395</CollectionWindowWidth>
  <CollectionWindowHeight>560</CollectionWindowHeight>
  <DefaultShowAllCards>false</DefaultShowAllCards>
  <NotifyNewDeckMissingCards>false</NotifyNewDeckMissingCards>
  <EnableDesiredCardsFeature>false</EnableDesiredCardsFeature>
</PluginSettings>`

**Comment by riQQ** [comment]
The config file doesn't have to be well-formatted. These should be separate issues. What's the error message when importing?

**Comment by miggat** [comment]
There is no exception caught, it just writes on the search field "fen creeper monica langlois", and hit enter, but then does nothing, no matter how much I wait.

HDT/CollectionTracker GUI are NOT frozen, but they aren't responsive either, so I need to close HDT from the task manager.

I have no idea where that "monica langlois" comes from!!

**Comment by ko-vasilev** [comment]
Okay I think I know the reason of issue.
"Monica Langlois" is the name of artist who drawn the art for card :)

**Comment by miggat** [comment]
Oh! I was wondering who Monica was.
I've download the code to try to fix it myself and spare you some work, but I couldn't build the solution, so I can't debug ;(

**Comment by ko-vasilev** [comment]
It's okay, I'll try to fix that in the evening.

**Comment by miggat** [comment]
It's working OK with the hotfix.
