### ISSUE TITLE
When changing the desired amount of a card in collection, the application crashes.

### ISSUE THREAD

**Issue by kevin-fang** [ko-vasilev/Hearthstone-Collection-Tracker#61]
[Crash report 28122015-107.txt](https://github.com/ko-vasilev/Hearthstone-Collection-Tracker/files/73299/Crash.report.28122015-107.txt)
[Crash report 28122015-945.txt](https://github.com/ko-vasilev/Hearthstone-Collection-Tracker/files/73300/Crash.report.28122015-945.txt)
[Crash report 28122015-953.txt](https://github.com/ko-vasilev/Hearthstone-Collection-Tracker/files/73298/Crash.report.28122015-953.txt)

After each crash, the entire collection is erased, having to import them again.

**Comment by ko-vasilev** [comment]
Can you confirm that issue still persists with latest version?

**Comment by kevin-fang** [comment]
I seem to be unable to reproduce the bug in the latest version.

**Comment by ko-vasilev** [comment]
Good,  thank you.
