### ISSUE TITLE
Gets Stuck on 0 Mana Tab While Exporting

### ISSUE THREAD

**Issue by poliwhirl555** [ko-vasilev/Hearthstone-Collection-Tracker#62]
As the title suggests, after the exported adds the first few zero mana cards, it leaves the zero mana tab on and the exporter keeps typing the names in and finding nothing. First experienced this issue when trying to export a Midrange hunter deck that started with one Hunters Mark, although I have tried with a rogue deck that had 2 Backstabs.

**Comment by riQQ** [comment]
I don't think this is a Hearthstone Collection Tracker issue but a [Hearthstone Deck Tracker issue](https://github.com/Epix37/Hearthstone-Deck-Tracker/issues).

**Comment by poliwhirl555** [comment]
Oops, did I post it in the wrong one, sorry! I'll repost on the other one.
