### ISSUE TITLE
Automatically update collection when open a new pack?

### ISSUE THREAD

**Issue by Ansem93** [ko-vasilev/Hearthstone-Collection-Tracker#64]
IT's possible to update the collection when I open a new pack?

**Comment by riQQ** [comment]
Right now, the pack opening isn't logged anymore. Blizzard broke this some time ago. We can only hope they fix it. Then the implementation in pull request #34 will update your collection automatically.

**Comment by culinko** [comment]
Also, this issue is just dupe of #24.

**Comment by ko-vasilev** [comment]
Yep, had plans on this but Blizz decided to disable ability to clearly track your pack openings.
