### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by Rtfyss** [ko-vasilev/Hearthstone-Collection-Tracker#65]
I am having difficulty installing the collection tracker in my deck tracker.  I installed the .dll in Hearthstone.Deck.Tracker-v0.13.7\Hearthstone Deck Tracker\Plugins and it does not operate nor show up in the decktracker plugins.  A step by step would be appreciated, especially one with pictures.

**Comment by riQQ** [comment]
Did you put everything directly in the Plugins folder? If you did, you should move the plugin to a subfolder like `Plugins\Hearthstone Collection Tracker\<plugin files and folders here>`

**Comment by Rtfyss** [comment]
yes.  everything I can attach a screenshot.

![deck tracker](https://cloud.githubusercontent.com/assets/16806829/12464181/c0f9dab0-bf95-11e5-9c81-bb9e8b42bf8f.png)

**Comment by Rtfyss** [comment]
Ok I followed your advice, created a new folder named as  you suggested, and it still does not appear in the plugins portion of deck tracker

**Comment by Rtfyss** [comment]
![deck tracker 2](https://cloud.githubusercontent.com/assets/16806829/12464274/2bb1fb58-bf96-11e5-89e9-d11765c51aeb.png)

**Comment by riQQ** [comment]
Have you unblocked the Dll (https://github.com/ko-vasilev/Hearthstone-Collection-Tracker#installation)?

**Comment by Rtfyss** [comment]
yes, it still does not show in deck tracker plugins

**Comment by riQQ** [comment]
It doesn't show under `Options > Tracker > Plugins`?

**Comment by Rtfyss** [comment]
![deck tracker 3](https://cloud.githubusercontent.com/assets/16806829/12464832/06d9529c-bf99-11e5-85b1-24f9e021c7f8.png)

**Comment by Rtfyss** [comment]
see, it is empty

**Comment by riQQ** [comment]
I'm talking about the Options page, not the Plugins menu in the toolbar.

**Comment by Rtfyss** [comment]
what options page

**Comment by riQQ** [comment]
At the top right of the program, there's a options button.

**Comment by Rtfyss** [comment]
ok, see it, turned it on, should that fix it? Is there anything else in options I should be concerned with?

**Comment by Rtfyss** [comment]
ok it is in deck tracker, now how do i get it to update from my collection in game?

**Comment by riQQ** [comment]
Go to your collection screen in Hearthstone, go to `Options > Tracker > Plugins` and select Collection Tracker. Open the Collection Tracker `Settings` via the button. In the settings dialog is a button `Import from Hearthstone`.

**Comment by Rtfyss** [comment]
ok, cannot find the collection tracker settings button

**Comment by riQQ** [comment]
![2016_01_20_23_31_40_hearthstone_deck_tracker](https://cloud.githubusercontent.com/assets/3404787/12465401/1c9da792-bfce-11e5-8964-7b078a85d7ef.png)

**Comment by Rtfyss** [comment]
aha, importing now.  Thank you very much.  There is not a clear tutorial for all of this, either in pictures or text.  You have been a huge help, thank you again.

**Comment by Rtfyss** [comment]
Issue Closed, much thanks to riQQ for assistance.

**Comment by ko-vasilev** [comment]
@riQQ thank you for helping with this. Will investigate if there is any way to implement "in-plugin guide". Or maybe just extend readme or wiki page.
