### ISSUE TITLE
Add function to sync collection with HearthPwn "My Collection"

### ISSUE THREAD

**Issue by Tropxe** [ko-vasilev/Hearthstone-Collection-Tracker#66]
Would this be possible? It would certainly be more efficient and convenient than the current method. For example, you can see my collection [here](http://www.hearthpwn.com/members/Winterfell/collection). It's updated automatically with their Innkeeper program so if you could make HCT sync automatically with that page, it would all be automated and very convenient indeed.

**Comment by ko-vasilev** [comment]
I asked them about any possibility for the integration, but unfortunately they kept silent.
