### ISSUE TITLE
Collection Tracker 0.2.4 is not compatible with HDT 0.13.11

### ISSUE THREAD

**Issue by schnapster** [ko-vasilev/Hearthstone-Collection-Tracker#68]
Collection Tracker 0.2.4 is not compatible with HDT 0.13.11

Getting following error upon trying to import:

![ss 2016-02-18 at 02 53 47](https://cloud.githubusercontent.com/assets/6048348/13131321/03eab59a-d5eb-11e5-8fc2-0c6696de7207.png)

**Comment by feriancek** [comment]
+1, same error. Windows 10 64bit if it matters.

**Comment by koppite** [comment]
Some information for what I got by playing around a bit.

I added plugin built from the latest source and it got past this error shown by op.  However it then got stuck reading the image (within the Hearthstone Deck Tracker), and therefore it never got past the first card of the collection (Fen Creeper).  

The only way I was able to fix this was to alter the HearthStoneDeckTracker function **CaptureHearthstone** in Hearthstone Deck Tracker\utility\helper.cs to by synchronous.   As it seemed the await inside **CaptureHearthstoneAsync** was never completing even though internally the Task was successfully grabbing a bmp of the required section.

I imagine the changing of this function inside the Deck Tracker project would have a more wider implication that someone over there would need to answer if it would impact other functionality by changing.

**Comment by ermosk** [comment]
Same issue here

**Comment by cachirro** [comment]
here too

**Comment by whyleee** [comment]
:+1:

**Comment by Stoutt** [comment]
Same error as well ... just in English.

**Comment by mssign** [comment]
:-@

**Comment by feriancek** [comment]
![image](https://cloud.githubusercontent.com/assets/5081442/13266596/34369990-da4f-11e5-970a-3f5567dc78ca.png)

Issue continues with newest release of HDT

**Comment by koppite** [comment]
As their don't seem to be any updates coming on here recently I have made the changes to make it compatible with 0.13.12 on my fork -> https://github.com/koppite/Hearthstone-Collection-Tracker/releases/tag/0.2.4.1

Let me know over there if there any issues.

**Comment by Ansem93** [comment]
I think that you should link your fork into the main page of HDT, This project is nearly dead after 5 months of 0 update :(
btw it works for me, so thank you a lot!
P.S. what's update collection?

**Comment by culinko** [comment]
This project is not dead. I'm pretty sure that author is just busy with his exams and will update it as soon as he can.

**Comment by ko-vasilev** [comment]
Fixed with cc26147c6936cc84c708b710e12adf1dde310f23.
