### ISSUE TITLE
Show "Account" name in main collection window

### ISSUE THREAD

**Issue by pagem** [ko-vasilev/Hearthstone-Collection-Tracker#69]
Is there anyway to show the current "Account" name in the main collection window? I have several accounts on each of the Hearthstone servers with different card collections and get confused which one I am in so it would be great if the collection name (account name) could appear somewhere in the main collection manager window. Thanks, great tool.

**Comment by ko-vasilev** [comment]
Yes I can do that for sure. Thank you.
