### ISSUE TITLE
Import Detection - Consistent Issues

### ISSUE THREAD

**Issue by Jademalo** [ko-vasilev/Hearthstone-Collection-Tracker#75]
I've imported my library 3 times now, and every time it makes a few of the same errors.
Before I import all, I flick through the whole library so that every card is "loaded" and it doesn't hang. 

I own every common and rare. However, a few commons and rares never seem to detect, no matter the settings I use. This happens regardless of importing all or importing a specific set, and these cards definitely show up and are searched for by the crawler. 
- Lightwell
- Mass Dispel
- Holy Fire
- Temple Enforcer
- Shadowboxer
- Velen's Chosen
- Upgraded Repair Bot
- Power Word: Glory
- Holy Champion.

No idea why this is, but it's really consistent. I've also just noticed it's only Priest cards. Weird!

**Comment by ko-vasilev** [comment]
Please check if these cards are imported as golden.

**Comment by Jademalo** [comment]
Yep, it seems like they have.

**Comment by ko-vasilev** [comment]
Okay, thank you for reporting. It is a known issue, currently working on fixing it.
