### ISSUE TITLE
Problem with importing

### ISSUE THREAD

**Issue by kacpero75** [ko-vasilev/Hearthstone-Collection-Tracker#76]
The collection tracker isnt finding any card, it seems like there is a problem with finding cards by author name. Standard in-game finding works fine but when i try to search for sth by author name it doesnt show any cards.

**Comment by ghost** [comment]
Same here. From what I understand, the problem is when the script put the name of the "artist" who made the card along with the name of the letter. This makes the HS does not recognize the name in the search and the script does not work. Solution: suffice to remove the names of the artists in the script's cards data base.

**Comment by LoveKC94** [comment]
Is it possible for us to remove the artists name from the script on our own?

**Comment by riQQ** [comment]
For information about filter changes see https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/2209.

**Comment by ghost** [comment]
Also having trouble with importing, returning no cards and essentially an 'empty' collection as a result.

**Comment by ghost** [comment]
I've opened the source but can't seem to find the database the extension uses for card names to remove the artist/author names. If anyone could tell me what the file is called I'd really appreciate it.

**Comment by depechenode** [comment]
today's patch I can no longer import decks either.  On first click it sets the mana gem to 0 then does not import any cards and states I am missing every card.

**Comment by depechenode** [comment]
ok my work around was setting Export speed to 3 seconds before starting.  This fixed all my issues on export

**Comment by ghost** [comment]
hey guys, increasing the speed to 3s helps in the main problem with the new update. But the problem in this topic is not how to unbug the export to hearstone, but with the plugin Hearthstone-Collection-Tracker. The program HS Deck Tracker already change the export script proprieties of the artists name (change to artist:name). But the problem with the Hearthstone-Collection-Tracker still is unchanged. Please fix the import script of Hearthstone-Collection-Tracker.
