### ISSUE TITLE
HDT error while trying to load the plugin

### ISSUE THREAD

**Issue by mobra** [ko-vasilev/Hearthstone-Collection-Tracker#77]
A weird error has been preventing me to use this collection tracker in the past 20-30 days. Apparently I didn't change anything, just updating regularly both the plugin and HDT. 
HDT correctly sees the plugin in its menu list, but when I try to activate it, it pops this error here:

![hdt error](https://cloud.githubusercontent.com/assets/5655652/13877848/9f871bcc-ed0d-11e5-9f1e-a86e13ee69a2.JPG)

Some XML file might be corrupted or absent, but I don't know which one.
I tried to start over with a clean install, but I'm having the same problem. Any thoughts?

**Comment by riQQ** [comment]
Open the config file located here `%APPDATA%\HearthstoneDeckTracker\CollectionTracker\config.xml` with a text editor and fix the malformed XML. If you don't know how to do that, upload it and I'll see if i can fix it.

**Comment by mobra** [comment]
Thank you, that was it ;)
Apparently, the XML content had been erased, so I just deleted it. Then, I launched HDT again and enabled the plugin, which worked. Finally, I went back to the newly generated config and changed a few lines, in order to point at my profile's collection XML, not the default one.
