### ISSUE TITLE
Import putting multiple phrases per search

### ISSUE THREAD

**Issue by carpathianmat** [ko-vasilev/Hearthstone-Collection-Tracker#78]
blizzard artist:seaman  mana:6inner fire artist:prescott  mana:1fen creeper artist:langlois  mana:5starfall artist:wright  mana:5kidnapper artist:allsop  mana:6mass dispel artist:o'daniels  mana:4shadowform artist:orlandelli  mana:3

An example search done by it, even on the slowest setting (running 32gb Ram, 3.6ghz i7, SSD etc etc, so shouldn't really be an issue??)

**Comment by ko-vasilev** [comment]
Does it ever clear the search box?

**Comment by carpathianmat** [comment]
Yeah occasionally one will get through and actually search fine, then it clears, then it goes back to pasting large amounts like above for a bit.

**Comment by carpathianmat** [comment]
https://www.youtube.com/watch?v=atM0IKCS47M&feature=youtu.be

**Comment by ko-vasilev** [comment]
Is that a surface?

**Comment by riQQ** [comment]
Try the first point here: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#exporting.

**Comment by campinoXL** [comment]
same here.
worked perfect for months, suddenly started to add <artist> to <card name> - and of course can't find anything ...
no matter which language is set by the way.
@riQQ: tried several tips mentioned there - none worked

**Comment by ko-vasilev** [comment]
@campinoXL are you using the latest version of collection tracker?

**Comment by campinoXL** [comment]
think I do, v0.3.1, file date is 01.03.2016 07:00

**Comment by riQQ** [comment]
v0.3.2 is the latest version

**Comment by campinoXL** [comment]
sorry, my fault.
didn't get the bookmark was kind of 'locked' at 0.3.1
newer version runs great again!
thanks

**Comment by ko-vasilev** [comment]
You're welcome!
