### ISSUE TITLE
Export collection to file

### ISSUE THREAD

**Issue by vlejd** [ko-vasilev/Hearthstone-Collection-Tracker#80]
Hi, 
would it be possible to add exporting to file? I can export collection from hearthstone to your plugin, but I would like to export it from your plugin to some file (anything that I can work with). Or is there some way to access this data from your plugin (any reasonable amount of programming is acceptable for me)?

**Comment by riQQ** [comment]
Your collections are saved at `%APPDATA%\HearthstoneDeckTracker\CollectionTracker\` in XML format.

**Comment by vlejd** [comment]
Thank you.
