### ISSUE TITLE
Whispers of the Old Gods update?

### ISSUE THREAD

**Issue by davidschwegler** [ko-vasilev/Hearthstone-Collection-Tracker#81]
Hey, any chance of an update in time for pack openings of the WOG update coming out in a couple days?

**Comment by ko-vasilev** [comment]
Hey, do you want to see something in particular?

**Comment by davidschwegler** [comment]
1) The same as the way the others work -- I'd just like to be able to see how complete my desired collection is after I open packs, like I can with the other expansions.
2) I'd love an "import" button under the expansion box itself, so I could import _only_ WOG set cards, though. It would be a lot faster than importing my entire collection, and I will be opening large packs several times.

**Comment by Mindereak** [comment]
I second this. Just need to implement the Whispers of the Old Gods set like you did with GvG, TgT, etc. so we can keep track of our new collection like we did with the past ones :)

**Comment by ko-vasilev** [comment]
Oh ok, I'll add the set for sure.
About import: you can specify which set to import before starting importing. I think this action is performed too rarely to put it in the main plugin window.

**Comment by davidschwegler** [comment]
Oh, OK thank you! I didn't realize you could specify that already.
