### ISSUE TITLE
Collection Tracker Keeps Crashing

### ISSUE THREAD

**Issue by Zanfai** [ko-vasilev/Hearthstone-Collection-Tracker#82]
[Crash report 2542016-148.txt](https://github.com/ko-vasilev/Hearthstone-Collection-Tracker/files/235184/Crash.report.2542016-148.txt)

Always does this when it gets to Gadgetzen Jouster

**Comment by leadingmore** [comment]
Had the exact same issue. Upgrading HDT caused the Collection manager data to be corrupted.  Cleaned up the files and tried reimporting, crashed HDT with the same error.  On Gadgetzen Jouster too.  100% reproducible.

**Comment by ko-vasilev** [comment]
I think it has something to do with recent HDT update. Unfortunately right now my computer is broken so I cannot fix it.

**Comment by Zanfai** [comment]
Should we roll back to the last update for the time being?
