### ISSUE TITLE
Can't enable Collection Tracker

### ISSUE THREAD

**Issue by Cedridor** [ko-vasilev/Hearthstone-Collection-Tracker#83]
![hdt collection tracker error](https://cloud.githubusercontent.com/assets/18692913/14841840/080cb552-0bff-11e6-8f22-17be1cd6f34d.png)

HDT starts with Collection Manager disabled, when I try to enable it, I get this. Using the latest version of HDT and Collection Manager, and the .dll is unblocked. Did I do something stupid?

**Comment by ko-vasilev** [comment]
I'll try to update the plugin within one day.
