### ISSUE TITLE
Newest release is still missing the Old Gods cards

### ISSUE THREAD

**Issue by culinko** [ko-vasilev/Hearthstone-Collection-Tracker#84]
The Old Gods set is still missing from the UI. Using 0.4.0.

Also, 2 minor things I would like to request (didn't want to open 2 more tickets for them). I'd like the vertical scrollbar to stay hidden if the window is small enough and I'd prefer if the zip files with releases also contained the version number. Thanks for all your work on this plugin!

![wotg](https://cloud.githubusercontent.com/assets/11700272/14861382/4d12dd12-0cad-11e6-91a5-58972b9493fe.png)

**Comment by riQQ** [comment]
Can confirm

**Comment by Cedridor** [comment]
After I imported the WotOG set showed up.

**Comment by culinko** [comment]
Yeah you are correct, it started appearing when I tried to add the relevant stuff manually to the Collection_Default.xml. I would still prefer a workaround without using the import function, though.

**Comment by culinko** [comment]
So, I imported the set and found out some issues:
- If the first card in the Collection_Default.xml is an Epic card, the sorting in the UI will also start with Epic cards and not commons (in the same screen as my initial screenshot)
- Some of the cards are sorted incorrectly. I believe the sorting recently in the HS collection was: mana cost, minions before spells (not sure about weapons), then alphabetically. For example Fiery Bat appears before On the Hunt in HS, but not in Collection Tracker.

**Comment by ko-vasilev** [comment]
Thank you for the feedback! Actually I remember cards used to be ordered by mana cost -> type -> name. Seems like Blizz changed that.

**Comment by culinko** [comment]
Perfect, thank you!
