### ISSUE TITLE
Crashing on attempting to start plugin

### ISSUE THREAD

**Issue by ghost** [ko-vasilev/Hearthstone-Collection-Tracker#88]
[Paste of Error](http://pastebin.com/6AyDpeyS)

Enabling the plugin and attempting to launch it crashes it. 

Other enabled plugins: HS Treasury, Arena Helper

**Comment by riQQ** [comment]
Same as https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2507.

**Comment by sdbds** [comment]
crashing at 0.14.8+

**Comment by anthenorjr** [comment]
Same problem, System Windows Interactivity Behaviorcollection exception.
Maybe windows 10 have something to do it?
I am able to open and use any other plugins, and the collection tracker options only from plugins inside hdt options.

**Comment by riQQ** [comment]
Maybe a bad combination of plugins?

**Comment by anthenorjr** [comment]
I don't think so, I tried using only the collection tracker and it's the same.

**Comment by riQQ** [comment]
Okay, can you go back and check with which version this bug was introduced?

**Comment by subinkim743** [comment]
Its 15.3 and I have no other plugins active.
You can reach the options from the hdt's plugin options and access the import function but the plugin ui itself doesn't run when you press the button from the main page and it crashes hdt.

**Comment by anthenorjr** [comment]
Well, I had exactly the same problem. But is loading now. I just removed all plugins, and worked even if I already did it before and it didn't worked. Other things happened to my PC at same time I don't think it was related, but who knows? Today I wake and my chrome was not loading pages, I reinstalled, ran chrome cleaner, bitdefender (nothing) and adwcleaner (found some minor stuff, idk).

**Comment by ghost** [comment]
same error - works fine if i remove my other plugins (arena tracker) though
maybe that's part of the problem?

**Comment by ko-vasilev** [comment]
Guys, please post here which plug-ins are you using besides the collection tracker.
