### ISSUE TITLE
Add value to collection of type 'System.Windows.Interactivity.BehaviorCollection' threw an exception

### ISSUE THREAD

**Issue by subinkim743** [ko-vasilev/Hearthstone-Collection-Tracker#91]
[Crash report 862016-1913.txt](https://github.com/ko-vasilev/Hearthstone-Collection-Tracker/files/304512/Crash.report.862016-1913.txt)

I hope this is the right place to post this question.

I can run all other plugins except this one.

**Comment by riQQ** [comment]
See #88.
