### ISSUE TITLE
Disenchanting not desired cards dust value

### ISSUE THREAD

**Issue by ioannis-mouratidis** [ko-vasilev/Hearthstone-Collection-Tracker#92]
I have marked any cards as "not desired", i.e. every card I'm missing should be desired, yet the average dust value per pack in parentheses (when disenchanting not desired cards) is different than the average dust value per pack.

Am I missing something or should it normally be the same?

**Comment by ko-vasilev** [comment]
Basically, in your case the difference is:
Consider you have 2 normal Leper Gnomes and you open a golden one
Value calculated in parenthesis assumes that you will disenchant it, and another value assumes that you'll keep it since you want 2 normal and 2 golden.

**Comment by ioannis-mouratidis** [comment]
Ah, ok, thanks for the quick clarification. I didn't realise golden cards are by default desired. I guess I should close this issue then.
