### ISSUE TITLE
Only imports ~10 cards from my entire collection.

### ISSUE THREAD

**Issue by tahornback** [ko-vasilev/Hearthstone-Collection-Tracker#93]
Hello,

I am trying to automatically input my collection into HCT and even at 150ms and all filters set correctly, it searches for cards for about 15 minutes (I think) and only adds 10 or so total cards to HCT. Is there a setting I missed or a bug that is easy to fix? If it's just changing a few lines of code I can do that myself.

Thanks,
Duxs

**Comment by tahornback** [comment]
In addition, I noticed that the aninmation of the crafting container in the corner is really studdery, maybe the game is lagging and preventing the cards from popping up?

Also, maybe the way the card description is put into the search bar is formatted incorrectly?

This is what I get when I created a new profile and ran a test import
![3da40209f6ed33d74a4b685a6e777483 1](https://cloud.githubusercontent.com/assets/6191956/15988617/2368121e-301d-11e6-8919-64a2ab029608.png)

**Comment by ko-vasilev** [comment]
During the search, do you actually see any cards appearing on the screen?

**Comment by tahornback** [comment]
Occasionally, but it is only the few cards that are actually imported (in that example, four) that come up when searching. Sometimes I think it does skip some that are there and doesn't recognize them.

**Comment by ko-vasilev** [comment]
Are you saying that during import you saw only 4 cards appearing in Hearthstone collection itself? What is your system language and what language is set on your keyboard during import?

**Comment by tahornback** [comment]
English for both. Before I start the import, it shows my full collection. When the import has started through the time it has finished, it only imports a few cards and also misses some other cards, but it never cycles through my full collection during the import process.

**Comment by tahornback** [comment]
Did another test import, recorded it this time https://youtu.be/iVSTe6GnpyE
HCT collection https://i.gyazo.com/0f4307752e655b0c80a1b5a8f48e67a4.png
If you need me to re-record it for any reason let me know

**Comment by ko-vasilev** [comment]
Oh I remember we had a similar issue, are you using a surface? Please try setting Win 7 compability mode for the Hearthstone, this should fix the issue.
Did you try using HDT "Export Deck to Hearthstone" functionality? It seems that it also might fail for you (if you won't set the compability mode).

**Comment by tahornback** [comment]
Thanks, that did the trick!
I am not using a surface, but I am using a touchscreen, and also a no on the deck export. As soon as I started the import it was behaving much differently than before, it appears that everything has been imported now!
